[package]
name = "rlsx"
description = "Parse Excel files in Rust"
authors = ["NEXORA Studios", "MoYuan-CN"]
readme = "README.md"
repository = "https://github.com/NEXORA-Studios/Lib.Rust.Rlsx"
license-file = "LICENSE"
keywords = ["excel", "xlsx", "parser", "rust"]
categories = ["parsing"]
version = "1.0.1"
edition = "2024"

[dependencies]
zip = "0.6.6"
quick-xml = "0.31.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
chrono = { version = "0.4.34", features = ["serde"] }
thiserror = "1.0.57"
